image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          # Install dependencies
          - apt-get update
          - apt-get -y install cmake pkg-config cppcheck mercurial build-essential lcov curl libprotobuf-dev protobuf-compiler libprotoc-dev libzmq3-dev uuid-dev doxygen ruby-ronn libsqlite3-dev
            libignition-msgs2-dev
          # Ignition cmake
          - hg clone http://bitbucket.org/ignitionrobotics/ign-cmake -b c++17
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition tools
          - hg clone http://bitbucket.org/ignitionrobotics/ign-tools
          - cd ign-tools
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition math
          - hg clone http://bitbucket.org/ignitionrobotics/ign-math -b gcc8_c++17
          - cd ign-math
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition msgs
          - hg clone http://bitbucket.org/ignitionrobotics/ign-msgs -b proto3
          - cd ign-math
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition Transport
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make -j4
          - make test ARGS="-VV"
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
          - make doc
          - make install
          - cd ..
          # Build examples
          - cd example
          - mkdir build && cd build
          - cmake ..
          - make -j4
          - cd ../..
          - cd log/example
          - mkdir build && cd build
          - cmake ..
          - make -j4
          - cd ../../..
          # Static checker
          - sh tools/code_check.sh
