image: ubuntu:16.04

pipelines:
  default:
    - step:
        script:
          - sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
          - sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-prerelease `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-prerelease.list'
          - cat /etc/apt/sources.list.d/gazebo-stable.list
          - cat /etc/apt/sources.list.d/gazebo-prerelease.list
          - apt-get update
          - apt-get -y install cmake pkg-config cppcheck libprotobuf-dev protobuf-compiler libprotoc-dev libzmq3-dev uuid-dev doxygen ruby-ronn libignition-msgs-dev
          - mkdir build
          - cd build
          - cmake ..
          - make -j4
          - make test ARGS="-VV"
          - make doc
          - cd ..
          - sh tools/code_check.sh
