image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          # Install dependencies
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list
          - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
          - apt-get update
          - apt-get -y install cmake pkg-config cppcheck mercurial build-essential lcov curl
            libprotobuf-dev protobuf-compiler libprotoc-dev libzmq3-dev uuid-dev doxygen ruby-ronn
            libsqlite3-dev
            libignition-tools-dev
            libignition-cmake1-dev
            libignition-math5-dev
            libignition-msgs2-dev
          # Ignition Transport
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make -j4
          - make test ARGS="-VV"
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
          - make doc
          - make install
          - cd ..
          # Build examples
          - cd example
          - mkdir build && cd build
          - cmake ..
          - make -j4
          - cd ../..
          # Static checker
          - sh tools/code_check.sh
